### ISSUE TITLE
Заменить Task<ModelResult<T>> на ModelResultTask<T>

### ISSUE THREAD

**Issue by Alex-Grigorichev** [Byndyusoft/Byndyusoft.ModelResult#15]
Task<ModelResult<T>> тяжело читается, предлагаем заменить на ModelResultTask<T>

**Comment by Rinatich** [comment]
Не получилось это реализовать из-за ограничений. Обсудим на болталке варианты.

**Comment by Alex-Grigorichev** [comment]
Обсудили на болталке, ничего нового не придумали, закрываем задачу.
